---
- name: Création du namespace postgresql
  shell: kubectl create namespace postgresql --dry-run=client -o yaml | kubectl apply -f -
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Création du secret superuser CloudNativePG
  shell: |
    kubectl create secret generic postgresql-superuser \
      -n postgresql \
      --from-literal=username=postgres \
      --from-literal=password='{{ vault_postgresql_password }}' \
      --dry-run=client -o yaml | kubectl apply -f -
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  no_log: true
