apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.longhorn.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 30m
  url: https://portainer.github.io/k8s/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gabe565
  namespace: flux-system
spec:
  interval: 30m
  type: oci
  url: oci://ghcr.io/gabe565/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: controlplaneio
  namespace: flux-system
spec:
  interval: 30m
  type: oci
  url: oci://ghcr.io/controlplaneio-fluxcd/charts