apiVersion: v1
kind: Service
metadata:
  name: postgresql-external
  namespace: postgresql
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: postgresql
    cnpg.io/instanceRole: primary
