---
- name: Installation via script officiel
  shell: curl -fsSL https://tailscale.com/install.sh | sh
  args:
    creates: /usr/bin/tailscale

- name: Configuration IP Forwarding (Master)
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  when: inventory_hostname in groups['master']

- name: Connexion Tailscale (Master - Routeur de sous-réseau)
  command: >
    tailscale up --authkey={{ tailscale_auth_key }}
    --advertise-routes=192.168.1.0/24
    --advertise-exit-node=false
    --accept-dns=false
    --ssh
  when: inventory_hostname in groups['master']

- name: Connexion Tailscale (Workers)
  command: >
    tailscale up --authkey={{ tailscale_auth_key }}
    --accept-dns=false
    --ssh
  when: inventory_hostname in groups['workers']

- name: Création du répertoire resolved.conf.d
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'

- name: Configuration DNS systemd-resolved vers AdGuard
  copy:
    dest: /etc/systemd/resolved.conf.d/adguard.conf
    content: |
      [Resolve]
      DNS={{ adguard_dns_ip }}
      Domains=~.
    mode: '0644'
  notify: Restart systemd-resolved