apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capacitor
  namespace: capacitor
spec:
  interval: 15m
  chart:
    spec:
      chart: capacitor-next
      version: "0.4.0"
      sourceRef:
        kind: HelmRepository
        name: gimlet
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
      hosts:
        - host: capacitor.k3s.home
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: capacitor-k3s-home-tls
          hosts:
            - capacitor.k3s.home
